"""
maxwell_exporter.py
将 B-H 曲线导出为 ANSYS Maxwell .amat 材料文件（AEDT $begin 格式）。
格式与 go_steel_data/output/GO_Steel_B23R075.amat 完全兼容，可被
bh_curve_analyzer.load_reference_materials() 和 Maxwell Import Material Library 直接读取。

Component1 = RD (Rolling Direction)
Component2 = TD (Transverse Direction)
Component3 = ND mu_r (scalar, default 1000)

NOTICE: core_loss_kh/kc/ke 为 Steinmetz/Bertotti 先验估算值，
非制造商实测多频 B-P 数据。生产级别使用请替换为供应商实测数据。
"""
import json
import os
from pathlib import Path
from datetime import datetime

from anisotropy_interpolator import MODEL_NAME
from physics_calibrator import calibrate_bh_curve, calibrate_material_pair


def _format_points_aedt(H: list, B: list) -> str:
    """
    Format H/B arrays as Maxwell AEDT Points[N: h1, b1, h2, b2, ...] string.
    Prepends (0, 0) origin point required by Maxwell for nonlinear BH data.
    N = 2 × number of (H, B) pairs (count of individual values, not pairs).
    """
    pairs = [(0.0, 0.0)] + [(float(h), float(b)) for h, b in zip(H, B) if h > 0]
    n = 2 * len(pairs)
    vals = ', '.join(f'{h:g}, {b:g}' for h, b in pairs)
    return f'Points[{n}: {vals}]'


def _estimate_core_loss_params(H: list, B: list,
                                thickness_mm: float = 0.35,
                                conductivity: float = 2.0e6,
                                reference_hc_am: float = None) -> dict:
    """
    从 B-H 曲线用 Steinmetz/Bertotti 先验估算铁损系数。
    EXPERIMENTAL — 仅供工程参考，非实测多频 B-P 数据。

    reference_hc_am: 若提供，使用参考数据库 Hc 值（推荐），否则从 B~0 处外插
                     （仿真 Hc ≈ 36000 A/m 会导致 kh 严重偏高）
    """
    import numpy as np
    import math
    mu0 = 4e-7 * math.pi
    H_arr = np.array(H, dtype=float)
    B_arr = np.array(B, dtype=float)
    valid = (H_arr > 0) & (B_arr > 0)
    if valid.sum() < 2:
        return {'kh': 5e-4, 'kc': 2e-5, 'ke': 3e-3}
    H_v = H_arr[valid]; B_v = B_arr[valid]
    Bm = float(np.max(B_v))
    # 磁滞损耗系数：μ₀·Hc/(π·Bm)
    # 优先使用参考数据库 Hc（< 10 A/m）；回退时从 B~0 外插（仿真值 ~36000 A/m，不可用）
    if reference_hc_am is not None:
        Hc_est = float(reference_hc_am)
    else:
        idx_min = int(np.argmin(np.abs(B_v)))
        Hc_est = float(np.abs(H_v[idx_min])) if idx_min > 0 else float(H_v[0])
    kh = mu0 * max(Hc_est, 1.0) / (math.pi * max(Bm, 0.1))
    # GO 硅钢 Hc < 10 A/m → kh ~ 1e-6，旧下限 1e-4 会截断参考 Hc 的影响。
    # 下限改为 1e-7（低于 GO 钢物理下限一个量级，留余量）。
    kh = float(np.clip(kh, 1e-7, 0.05))
    # 涡流损耗系数：π²σd²/6
    d = thickness_mm * 1e-3
    kc = (math.pi ** 2) * conductivity * (d ** 2) / 6.0
    kc = float(np.clip(kc, 1e-6, 1e-3))
    # 附加损耗系数：GO 钢经验先验
    ke = float(np.clip(0.002 * Bm, 1e-4, 0.02))
    return {'kh': kh, 'kc': kc, 'ke': ke}


def _preprocess_bh(H: list, B: list) -> tuple[list, list]:
    """
    预处理 B-H 数据：去掉 H<=0，排序，去重，确保 B 单调不减。
    返回 (H_clean, B_clean)。
    """
    guarded = calibrate_bh_curve(H, B, source='maxwell_exporter')
    return guarded['H'], guarded['B']


def _metadata_path_for_amat(path: Path) -> Path:
    return path.with_suffix('.metadata.json')


def _write_metadata(path: Path, metadata: dict) -> str:
    meta_path = _metadata_path_for_amat(path)
    payload = {
        'generated_at': datetime.now().isoformat(),
        'amat_path': str(path),
        **(metadata or {}),
    }
    meta_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
    return str(meta_path)


def generate_amat_content(mat_name: str,
                           rd_H: list, rd_B: list,
                           td_H: list = None, td_B: list = None,
                           nd_mu_r: float = 1000.0,
                           density_kg_m3: float = 7650.0,
                           thickness_mm: float = 0.35,
                           conductivity: float = 2.0e6,
                           core_loss_override: dict = None,
                           reference_hc_am: float = None) -> str:
    """
    生成 ANSYS Maxwell AEDT $begin 格式的完整 .amat 文件内容。
    格式与 go_steel_data/output/GO_Steel_B23R075.amat 完全兼容。

    td_H/td_B 为 None 时，TD 与 RD 相同（各向同性退化）。
    core_loss_override: 若提供 {'kh':…,'kc':…,'ke':…} 则覆盖估算值。
    reference_hc_am: GO 钢参考矫顽力 [A/m]，用于计算 kh（磁滞损耗系数）。
                     建议传入 go_steel_reference.get_reference_hc()；
                     不传则回退到从 B-H 曲线外插（仿真值约 36000 A/m，kh 严重偏高）。
    """
    if td_H is None or td_B is None:
        td_H, td_B = rd_H, rd_B

    rd_H_c, rd_B_c = _preprocess_bh(rd_H, rd_B)
    td_H_c, td_B_c = _preprocess_bh(td_H, td_B)

    cl = core_loss_override or _estimate_core_loss_params(
        rd_H_c, rd_B_c, thickness_mm=thickness_mm, conductivity=conductivity,
        reference_hc_am=reference_hc_am)

    rd_pts = _format_points_aedt(rd_H_c, rd_B_c)
    td_pts = _format_points_aedt(td_H_c, td_B_c)
    kh = cl.get('kh', 5e-4)
    kc = cl.get('kc', 2e-5)
    ke = cl.get('ke', 3e-3)
    thickness_m = thickness_mm * 1e-3

    return (
        f"# Maxwell material library — {mat_name}\n"
        f"# Generated by GO steel micromagnetic simulation pipeline\n"
        f"# Component1=RD (Rolling Direction), Component2=TD (Transverse Direction), Component3=ND mu_r={nd_mu_r:.0f}\n"
        f"# NOTICE: core_loss_kh/kc/ke are EXPERIMENTAL ESTIMATES (Steinmetz/Bertotti priors).\n"
        f"#   NOT manufacturer-measured B-P data. Replace with supplier datasheet values for production use.\n"
        f"\n"
        f"$begin '{mat_name}'\n"
        f"\t'CoordinateSystemType'='Cartesian'\n"
        f"\t'BulkOrSurface'='Bulk'\n"
        f"\t$begin 'PhysicsTypes'\n"
        f"\t\t'set'('Electromagnetic')\n"
        f"\t$end 'PhysicsTypes'\n"
        f"\t$begin 'AttachedData'\n"
        f"\t$end 'AttachedData'\n"
        f"\t$begin 'ModifierData'\n"
        f"\t\t$begin 'ThermalModifierData'\n"
        f"\t\t\t'modifier_data'='no_modifier'\n"
        f"\t\t$end 'ThermalModifierData'\n"
        f"\t$end 'ModifierData'\n"
        f"\t'permittivity'='1'\n"
        f"\t$begin 'permeability'\n"
        f"\t\t'property_type'='AnisoProperty'\n"
        f"\t\t$begin 'component1'\n"
        f"\t\t\t'property_type'='nonlinear'\n"
        f"\t\t\t'BTypeForSingleCurve'='Normal'\n"
        f"\t\t\t'HUnit'='A_per_meter'\n"
        f"\t\t\t'BUnit'='tesla'\n"
        f"\t\t\t'IsTemperatureDependent'=false\n"
        f"\t\t\t$begin 'BHCoordinates'\n"
        f"\t\t\t\t'DimUnits'('')\n"
        f"\t\t\t\t{rd_pts}\n"
        f"\t\t\t\t$begin 'Temperatures'\n"
        f"\t\t\t\t$end 'Temperatures'\n"
        f"\t\t\t$end 'BHCoordinates'\n"
        f"\t\t$end 'component1'\n"
        f"\t\t$begin 'component2'\n"
        f"\t\t\t'property_type'='nonlinear'\n"
        f"\t\t\t'BTypeForSingleCurve'='Normal'\n"
        f"\t\t\t'HUnit'='A_per_meter'\n"
        f"\t\t\t'BUnit'='tesla'\n"
        f"\t\t\t'IsTemperatureDependent'=false\n"
        f"\t\t\t$begin 'BHCoordinates'\n"
        f"\t\t\t\t'DimUnits'('')\n"
        f"\t\t\t\t{td_pts}\n"
        f"\t\t\t\t$begin 'Temperatures'\n"
        f"\t\t\t\t$end 'Temperatures'\n"
        f"\t\t\t$end 'BHCoordinates'\n"
        f"\t\t$end 'component2'\n"
        f"\t\t'component3'='{nd_mu_r:.0f}'\n"
        f"\t$end 'permeability'\n"
        f"\t'conductivity'='{conductivity:.0f}'\n"
        f"\t'Tref'='22cel'\n"
        f"\t'mass_density'='{density_kg_m3:.0f}'\n"
        f"\t$begin 'core_loss_type'\n"
        f"\t\t'property_type'='ChoiceProperty'\n"
        f"\t\t'Choice'='Electrical Steel'\n"
        f"\t$end 'core_loss_type'\n"
        f"\t'core_loss_kh'='{kh:.6e}'\n"
        f"\t'core_loss_kc'='{kc:.6e}'\n"
        f"\t'core_loss_ke'='{ke:.6e}'\n"
        f"\t'core_loss_kdc'='0'\n"
        f"\t'core_loss_equiv_cut_depth'='{thickness_m:.5f}meter'\n"
        f"\t'SolveInside'='1'\n"
        f"$end '{mat_name}'\n"
    )


def save_amat_file(content: str, mat_name: str,
                   export_dir: str = 'data/exports',
                   metadata: dict = None) -> str:
    """保存到 data/exports/<mat_name>.amat，返回文件路径。"""
    Path(export_dir).mkdir(parents=True, exist_ok=True)
    path = Path(export_dir) / f'{mat_name}.amat'
    path.write_text(content, encoding='utf-8')
    if metadata is not None:
        _write_metadata(path, metadata)
    return str(path)


def export_from_bh_curves(rd_H: list, rd_B: list,
                           td_H: list = None, td_B: list = None,
                           mat_name: str = None,
                           thickness_mm: float = 0.35,
                           export_dir: str = 'data/exports',
                           source: str = None) -> str:
    """
    从手动 B-H 数据生成并保存 .amat 文件，返回文件路径。
    mat_name 为 None 时自动生成时间戳命名。
    """
    if mat_name is None:
        mat_name = f'GO_Sim_{datetime.now().strftime("%Y%m%d_%H%M%S")}'
    if td_H is None or td_B is None:
        td_H, td_B = rd_H, rd_B
    pair = calibrate_material_pair(
        {'H': rd_H, 'B': rd_B, 'source': source or 'manual_export_RD'},
        {'H': td_H, 'B': td_B, 'source': source or 'manual_export_TD'},
    )
    content = generate_amat_content(mat_name, rd_H, rd_B, td_H, td_B,
                                    thickness_mm=thickness_mm)
    metadata = {
        'material_name': mat_name,
        'source': source,
        'rd_td_calibration_summary': pair['report'],
        'full_direction_generated': False,
        'interpolation_model': MODEL_NAME,
        'exported_directions': ['RD', 'TD'],
    }
    return save_amat_file(content, mat_name, export_dir, metadata=metadata)


def export_from_prediction(prediction_result: dict,
                            mat_name: str,
                            thickness_mm: float = 0.35,
                            export_dir: str = 'data/exports') -> str:
    """
    从 BHPredictor.predict_bh() 的返回值直接生成 .amat。
    prediction_result 格式：{'RD': {'H':[...], 'B':[...]}, 'TD': {...}, ...}
    """
    from go_steel_reference import get_reference_hc
    rd = prediction_result.get('RD', {})
    td = prediction_result.get('TD', {})
    # 优先使用 predict_bh() 已嵌入的参考 Hc；否则按 Si_content 查表
    ref_hc = prediction_result.get('Hc_reference_Am')
    if ref_hc is None:
        si_content = float((prediction_result.get('params_used') or {}).get('Si_content', 3.0))
        ref_hc = get_reference_hc(si_content=si_content)
    pair = calibrate_material_pair(
        {'H': rd.get('H', []), 'B': rd.get('B', []), 'source': 'prediction_RD'},
        {'H': td.get('H', []), 'B': td.get('B', []), 'source': 'prediction_TD'},
    )
    content = generate_amat_content(
        mat_name,
        rd.get('H', []), rd.get('B', []),
        td.get('H', []), td.get('B', []),
        thickness_mm=thickness_mm,
        reference_hc_am=ref_hc,
    )
    metadata = {
        'material_name': mat_name,
        'source_model_id': prediction_result.get('model_id') or prediction_result.get('model_metadata', {}).get('model_id'),
        'rd_td_calibration_summary': pair['report'],
        'full_direction_generated': bool(prediction_result.get('full_direction')),
        'interpolation_model': MODEL_NAME,
        'exported_directions': ['RD', 'TD'],
    }
    return save_amat_file(content, mat_name, export_dir, metadata=metadata)


def list_exports(export_dir: str = 'data/exports') -> list[dict]:
    """列出 data/exports/ 下所有 .amat 文件的元信息。"""
    result = []
    d = Path(export_dir)
    if not d.exists():
        return result
    for f in sorted(d.glob('*.amat'), reverse=True):
        result.append({
            'name':    f.name,
            'path':    str(f),
            'metadata_path': str(_metadata_path_for_amat(f)) if _metadata_path_for_amat(f).exists() else None,
            'size_kb': round(f.stat().st_size / 1024, 1),
            'created': datetime.fromtimestamp(f.stat().st_mtime).strftime('%Y-%m-%d %H:%M:%S'),
        })
    return result
