const assert=require('node:assert/strict');
const {plotData,chartMarkup,esc}=require('../static/js/motor_waveforms.js');
const record={time_ms:[0,10,20,30],selected_window_ms:[20,30],series:{torque:[-1,0,1,2],core_loss:[0,1,1,1]}};
const original=JSON.stringify(record);
const raw=plotData([record],'torque',true);
assert.deepEqual(raw.lines[0].points.map(p=>p.v),[-1,0,1,2]);
assert.ok(raw.min< -1&&raw.max>2);
const windowed=plotData([record],'torque',false);
assert.deepEqual(windowed.lines[0].points.map(p=>p.t),[20,30]);
assert.equal(windowed.start,20);
assert.equal(windowed.stop,30);
assert.equal(plotData([record],'solid_loss',true).lines.length,0);
const zero=plotData([{...record,series:{torque:[0,0,0,0]}}],'torque',true);
assert.ok(zero.min<0&&zero.max>0);
assert.ok(!/NaN|Infinity/.test(chartMarkup(zero,350)));
const html=chartMarkup(plotData([record,{...record,series:{torque:[2,2,2,2]}}],'torque',true),560);
assert.equal((html.match(/<polyline /g)||[]).length,2);
assert.ok(html.includes('时间 / ms'));
assert.equal(JSON.stringify(record),original);
assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;');
console.log('Official waveform points, metric window, signs and zero-range UI: PASS');
